#!/usr/bin/env bash
# Script that will display information about subdomains.

domain=$1
subdomain=$2

if [ "$#" -eq 1 ]; then
	echo "$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{split($1, parts, ".");print "The subdomain " parts[1] " is a " $4 " record and points to " $5}'
fi
