#!/usr/bin/env bash
# Check if the correct number of arguments are passed
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign the arguments to variables for better readability
FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Use scp to transfer the file
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$SERVER_IP":~/
