#!/usr/bin/env bash
# change localhost to 127.0.0.2
# change facebook to 8.8.8.8
new_localhost="127.0.0.2"
new_fb="8.8.8.8"
cp /etc/hosts/ ~/hosts.new
sed -i "s/127.*$/$new_localhost" ~/hosts.new
sed -i "1s/^/$new_fb facebook.com\n/" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
