#!/usr/bin/env bash
-- Uses ssh to connect to your server using the private key
-- ~/.ssh/school with the user ubuntu.
server="3.85.196.229"
user="ubuntu"
key="~/.ssh/school"

ssh -i $key $user@$server
